names = [
    "Bella", "Max", "Luna", "Charlie", "Lucy", "Cooper", "Daisy", "Bailey", "Sadie", "Oliver",
    "Molly", "Tucker", "Riley", "Maggie", "Bear", "Sophie", "Chloe", "Buddy", "Zoe", "Stella",
    "Lola", "Penny", "Bentley", "Jack", "Duke", "Roxy", "Harley", "Lily", "Loki", "Zoey",
    "Roxie", "Milo", "Ruby", "Oscar", "Gus", "Sam", "Rosie", "Ellie", "Abby", "Winston",
    "Koda", "Louie", "Murphy", "Coco", "Gracie", "Izzy", "Leo", "Scout", "Jasper", "Mia",
    "Finn", "Marley", "Rocky", "Moose", "Hank", "Shadow", "Blue", "Ginger", "Piper", "Lulu",
    "Nala", "Buster", "Dexter", "Minnie", "Diesel", "Pearl", "Tank", "Lady", "Thor", "Cleo",
    "Jax", "Rudy", "Olive", "Apollo", "Ace", "Belle", "Boomer", "Frankie", "Annie", "Ollie",
    "Toby", "Benji", "Theo", "Sammy", "Bruno", "Bo", "Layla", "Simba", "Sasha", "Zeus",
    "Henry", "Cali", "Hazel", "Hunter", "Willow", "Juno", "Chief", "Ranger", "Leia", "Bandit",
    "Holly", "Chester", "Otis", "Simba", "Bruce", "Copper", "Luke", "Kona", "Jackie", "Casey",
    "Rocco", "Remy", "Gunner", "Prince", "Samson", "Leon", "George", "Frank", "Sunny", "Mac",
    "Murph", "Joey", "Archie", "Beau", "Scooter", "Jasmine", "Pepper", "Fiona", "Walter", "Chase",
    "Socks", "Tito", "Bean", "Rascal", "Lenny", "Lucky", "Spike", "Baxter", "Maverick", "Barney",
    "Otto", "Scooby", "Tiger", "Benny", "Cody", "Cash", "Kobe", "Boots", "Bonnie", "Fluffy",
    "Mocha", "Maddie", "Bruce", "Gizmo", "Lou", "Betty", "Cesar", "Goose", "Hugo", "Winnie",
    "August", "Sylvester", "Violet", "Blu", "Quincy", "Rex", "Dolly", "Trixie", "Felix", "Calvin",
    "Gigi", "Nina", "Moose", "Honey", "Panda", "Ivy", "Echo", "Paris", "Athena", "Louie",
    "Patches", "Raven", "Blaze", "Buttercup", "Ava", "Alfie", "Misty", "Cookie", "Elliot", "Lenny",
    "Mango", "Phoebe", "Edgar", "Dakota", "Josie", "Colby", "Monty", "Harvey", "Miles", "Chip",
    "Jojo", "Oreo", "Dudley", "Pepper", "Chewy", "Mack", "Bubba", "Bruce", "Digby", "Spencer",
    "Jinx", "Pluto", "Tyson", "Jade", "Nikki", "Axel", "Dot", "Mabel", "Sparky", "Sabrina",
    "Lincoln", "Biscuit", "Dino", "Reggie", "Whiskey", "Sky", "Nero", "Salem", "Newton", "Jett",
    "Freddie", "Rufus", "Buzz", "Bodhi", "Hank", "Pablo", "Cupcake", "Champ", "Dora", "Ringo",
    "Bridget", "Aldo", "Fergie", "Rigby", "Teddy", "Snickers", "Buffy", "Bruce", "Bolt", "Cassie",
    "Chico", "Clyde", "Cricket", "Darwin", "Elvis", "Floyd", "Gatsby", "Harper", "Hershey", "Jellybean",
    "Kai", "Kira", "Kiwi", "Lacey", "Lassie", "Lexi", "Linguine", "Maple", "Marbles", "Meatball",
    "Merlin", "Mittens", "Muffin", "Nacho", "Nimbus", "Ozzy", "Peaches", "Pebbles", "Pesto", "Pippin",
    "Pixel", "Poe", "Poncho", "Poppy", "Pumpkin", "Quinn", "Ramen", "Rex", "Rizzo", "Robin",
    "Rocket", "Romeo", "Rosco", "Rusty", "Sable", "Sage", "Scamp", "Scarlett", "Scrappy", "Shelby",
    "Shiloh", "Smokey", "Snickerdoodle", "Soda", "Spud", "Squirt", "Stitch", "Sushi", "Taco", "Tessa",
    "Tofu", "Trudy", "Twix", "Velvet", "Watson", "Wesley", "Whiskers", "Wrigley", "Yoda", "Yoshi",
    "Zelda", "Ziggy", "Zippy", "Zuzu", "Avery", "Baron", "Bingo", "Bolt", "Bootsie", "Brandy",
    "Brody", "Brownie", "Butters", "Caesar", "Carmen", "Cheddar", "Cheeky", "Chiquita", "Cinder",
    "Clifford", "Clover", "Coco Chanel", "Comet", "Cosmo", "Crash", "Cuddles", "Cyrus", "Dante",
    "Darla", "Delilah", "Denzel", "Diva", "Dobby", "Domino", "Donatello", "Dozer", "Draco", "Duchess",
    "Duffy", "Eddie", "Einstein", "Elmo", "Ember", "Enzo", "Fancy", "Fido", "Figaro", "Finnegan",
    "Fletcher", "Flo", "Frodo", "Fuzzy", "Gadget", "Galaxy", "Gary", "Gilligan", "Goldie", "Gretel",
    "Griffin", "Guinness", "Hamlet", "Herschel", "Hobbes", "Hopper", "Igor", "Indy", "Iris", "Iroh",
    "Ivory", "Java", "Jelly", "Jerry", "Jewel", "Jingles", "Joker", "Julius", "June", "Kahlua",
    "Kermit", "Kiara", "Kiki", "King", "Kipper", "Klaus", "Klein", "Koko", "Kona", "Kylo",
    "Lancelot", "Latte", "Levi", "Libby", "Lola Bunny", "Ludo", "Luigi", "Luna Lovegood", "Lyric", "Macaroon",
    "Madonna", "Malcolm", "Marmaduke", "Marshmallow", "Matilda", "Maui", "Maximus", "Maya", "McGonagall", "McGruff",
    "McKinley", "Meadow", "Merlot", "Midnight", "Mika", "Milan", "Millie", "Moby", "Mona", "Morty",
    "Mouse", "Mr. Bigglesworth", "Mulan", "Munchkin", "Murdock", "Myrtle", "Nala", "Napoleon", "Nessie", "Newton",
    "Nibbler", "Nickel", "Nikita", "Nimbus", "Noel", "Noodles", "Nova", "Nugget", "Nutella", "Octavia",
    "Odin", "Olaf", "Ophelia", "Orbit", "Orion", "Paisley", "Paloma", "Pascal", "Paws", "Peanut Butter",
    "Pear", "Penelope", "Percy", "Picasso", "Pierre", "Pinky", "Pirate", "Polly", "Poncho", "Popcorn",
    "Poptart", "Porter", "Praline", "Presley", "Pretzel", "Primrose", "Prince Charming", "Puck", "Pudding", "Puffin",
    "Queso", "Quimby", "Radar", "Raleigh", "Rambo", "Ramses", "Ranger", "Ravioli", "Reeses", "Rey",
    "Rhett", "Rigsby", "Ripley", "River", "Rizzo", "Rooney", "Roscoe", "Rosemary", "Rowan", "Roxanne",
    "Rufio", "Sable", "Saffron", "Sage", "Sailor", "Sake", "Salem", "Samus", "Sandy", "Santana",
    "Sapphire", "Sarabi", "Sarge", "Sasha Fierce", "Sassy", "Scooby Doo", "Scout", "Scrappy", "Scruffles", "Seamus",
    "Sebastian", "Seraphina", "Sergeant", "Shadow", "Shamus", "Sheldon", "Sherlock", "Shiloh", "Sierra", "Silver",
    "Simone", "Sirius", "Sissy", "Skippy", "Skye", "Slinky", "Smokey Bear", "Snickers", "Soda Pop", "Solomon",
    "Sonny", "Sookie", "Spanky", "Spartacus", "Spice", "Spike", "Spirit", "Spooky", "Sprinkles", "Squash",
    "Squirrel", "Stanley", "Star", "Stella Luna", "Sterling", "Steve", "Stewie", "Storm", "Sugar", "Suki",
    "Sundance", "Sushi", "Sweet Pea", "Sweetie", "Sydney", "T-Bone", "Tabitha", "Taco", "Talia", "Tango",
    "Tasha", "Tater Tot", "Taz", "Tequila", "Tesla", "Thaddeus", "Theodore", "Thor", "Thumbelina", "Tiana",
    "Tiger Lily", "Tilly", "Timber", "Tinkerbell", "Tiny", "Tito", "Toast", "Toffee", "Tootsie", "Topaz",
    "Trapper", "Trixie", "Troy", "Truffle", "Tulip", "Turbo", "Twilight", "Twinkie", "Tyson", "Ulysses",
    "Uma", "Ursula", "Valentino", "Vanilla", "Velma", "Venus", "Vinnie", "Violet", "Vito", "Waffles",
    "Wallace", "Wanda", "Watson", "Wesley", "Weston", "Whiskey", "Whitney", "Widget", "Wilbur", "Wilfred",
    "Willow", "Willy Wonka", "Wilson", "Winnie the Pooh", "Winston", "Winter", "Wolfgang", "Woody", "Xander", "Xena",
    "Yara", "Yeller", "Yeti", "Yin", "Yogi", "Yoshi", "Yukon", "Yumi", "Yvette", "Zachary",
    "Zara", "Zeppelin", "Zero", "Ziggy Stardust", "Ziti", "Zoe", "Zola", "Zorro", "Zulu", "Zuzu"
]
